# Generated by Django 3.0.5 on 2020-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rejister'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejister',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
